# Application for Configuration of API Gateway
# Responsibilities:
# - Configures server port
# - Sets up Redis connection details
# - Configures Resilience4j circuit breaker settings
# - Defines API Gateway routes and filters

server:
  port: 8080

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
              - "http://localhost:3000"
              - "http://localhost:5175"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      httpclient:
        connect-timeout: 5000 # milliseconds
        response-timeout: 10s
        pool:
          type: elastic
          max-connections: 200
          acquire-timeout: 500
      routes:
        # Route to Orchestrator
        - id: orchestrator-service
          uri: ${ORCHESTRATOR_URI:http://orchestrator:8082}
          predicates:
            - Path=/api/v1/orchestrator/**
          filters:
#            - name: RequestRateLimiter
#              args:
#                key-resolver: "#{@ipKeyResolver}"
#                redis-rate-limiter.replenishRate: 10
#                redis-rate-limiter.burstCapacity: 20
            - name: CircuitBreaker
              args:
                name: orchestratorCircuitBreaker
                fallbackUri: forward:/fallback/orchestrator

      # Global filters
      default-filters:
        - AddRequestHeader=X-Gateway-Request, ApiGateway
        - AddResponseHeader=X-Gateway-Response, ApiGateway

resilience4j:
  circuitbreaker:
    instances:
      orchestratorCircuitBreaker:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 50
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s



